# Generated by Django 4.2.30 on 2026-09-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('ERP', 'ERP'), ('MES', 'MES'), ('CRM', 'CRM'), ('WMS', 'WMS'), ('GENERICO', 'Genérico')], default='GENERICO', max_length=20)),
                ('protocolo', models.CharField(choices=[('REST', 'REST / JSON'), ('SOAP', 'SOAP / WSDL'), ('XMLRPC', 'XML-RPC'), ('ODATA', 'OData'), ('GRAPHQL', 'GraphQL')], max_length=20)),
                ('base_url', models.URLField()),
                ('ativo', models.BooleanField(default=True)),
                ('adapter_customizado', models.CharField(blank=True, max_length=120)),
                ('tipo_auth', models.CharField(choices=[('NONE', 'Sem autenticação'), ('BEARER', 'Bearer Token (estático)'), ('API_KEY', 'API Key (header/query)'), ('BASIC', 'Basic Auth'), ('OAUTH2_CC', 'OAuth2 Client Credentials'), ('CUSTOM', 'Strategy customizada')], default='NONE', max_length=20)),
                ('credenciais_cifradas', models.BinaryField(blank=True, null=True)),
                ('auth_extra', models.JSONField(blank=True, default=dict)),
                ('timeout_segundos', models.PositiveIntegerField(default=30)),
                ('headers_padrao', models.JSONField(blank=True, default=dict)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('falhas_consecutivas', models.PositiveIntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('webhook_habilitado', models.BooleanField(default=False)),
                ('webhook_hmac_atual_cifrado', models.BinaryField(blank=True, null=True)),
                ('webhook_hmac_anterior_cifrado', models.BinaryField(blank=True, null=True)),
                ('webhook_auth_strategy', models.CharField(blank=True, default='HMAC_SHA256', help_text='Chave da strategy no registry. Ex: HMAC_SHA256, GITHUB, STRIPE, HMAC_SHA1', max_length=60)),
                ('webhook_auth_params', models.JSONField(blank=True, default=dict)),
                ('webhook_tolerancia_segundos', models.PositiveIntegerField(default=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sistema Externo',
                'verbose_name_plural': 'Sistemas Externos',
            },
        ),
        migrations.CreateModel(
            name='WebhookRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=120)),
                ('headers', models.JSONField(default=dict)),
                ('corpo', models.JSONField(blank=True, null=True)),
                ('assinatura_recebida', models.CharField(blank=True, max_length=255)),
                ('assinatura_valida', models.BooleanField(blank=True, null=True)),
                ('delivery_id', models.CharField(blank=True, db_index=True, help_text='ID único do emissor para idempotência (X-Delivery-ID, X-Event-ID, etc.)', max_length=200)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('processado', models.BooleanField(db_index=True, default=False)),
                ('processando', models.BooleanField(default=False)),
                ('tentativas_processamento', models.PositiveIntegerField(default=0)),
                ('erro', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('sistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integracao.sistemaexterno')),
            ],
            options={
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao_codigo', models.CharField(max_length=120)),
                ('direcao', models.CharField(choices=[('REQUEST', 'Requisição (nós → eles)'), ('RESPONSE', 'Resposta (eles → nós)'), ('WEBHOOK', 'Webhook (entrada)')], max_length=10)),
                ('payload_original', models.JSONField(blank=True, null=True)),
                ('payload_mapeado', models.JSONField(blank=True, null=True)),
                ('resposta_bruta', models.JSONField(blank=True, null=True)),
                ('resposta_mapeada', models.JSONField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('duracao_ms', models.IntegerField(default=0)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('dry_run', models.BooleanField(db_index=True, default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integracao.sistemaexterno')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OperacaoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField()),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('metodo_http', models.CharField(default='POST', max_length=10)),
                ('caminho', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/json', max_length=80)),
                ('adapter_params', models.JSONField(blank=True, default=dict)),
                ('schema_entrada', models.JSONField(blank=True, null=True)),
                ('schema_saida', models.JSONField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('prioridade', models.PositiveSmallIntegerField(default=5)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='integracao.sistemaexterno')),
            ],
        ),
        migrations.CreateModel(
            name='MapeamentoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direcao', models.CharField(choices=[('REQUEST', 'Requisição (nós → eles)'), ('RESPONSE', 'Resposta (eles → nós)'), ('WEBHOOK', 'Webhook (entrada)')], max_length=10)),
                ('origem_path', models.CharField(max_length=255)),
                ('destino_path', models.CharField(max_length=255)),
                ('transformacoes', models.JSONField(default=list)),
                ('valor_padrao', models.JSONField(blank=True, null=True)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos', to='integracao.operacaointegracao')),
            ],
            options={
                'ordering': ['operacao', 'direcao', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('INTEGRACAO', 'Integração (saída)'), ('WEBHOOK', 'Webhook (entrada)')], max_length=20)),
                ('operacao_codigo', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('ultima_excecao', models.TextField(blank=True)),
                ('ultima_excecao_tipo', models.CharField(blank=True, max_length=120)),
                ('total_tentativas', models.PositiveIntegerField(default=0)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de reprocessamento'), ('REPROCESSANDO', 'Reprocessando'), ('RESOLVIDO', 'Resolvido'), ('DESCARTADO', 'Descartado')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('registro_integracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integracao.registrointegracao')),
                ('sistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integracao.sistemaexterno')),
                ('webhook_recebido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integracao.webhookrecebido')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookrecebido',
            index=models.Index(fields=['sistema', 'evento', 'recebido_em'], name='integracao__sistema_025131_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookrecebido',
            index=models.Index(fields=['delivery_id'], name='integracao__deliver_f0a4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='registrointegracao',
            index=models.Index(fields=['sistema', 'operacao_codigo', 'criado_em'], name='integracao__sistema_1443e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operacaointegracao',
            unique_together={('sistema', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='deadletterqueue',
            index=models.Index(fields=['status', 'criado_em'], name='integracao__status_07f5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='deadletterqueue',
            index=models.Index(fields=['origem', 'sistema'], name='integracao__origem_2a04b8_idx'),
        ),
    ]
