# Generated by Django 4.2.30 on 2026-07-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prefab_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.CharField(max_length=100)),
                ('gameobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unity.gameobject')),
            ],
        ),
        migrations.CreateModel(
            name='GameObjectTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unity.gameobject')),
            ],
        ),
        migrations.CreateModel(
            name='GameObjectScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('game_object_transform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unity.gameobjecttransform')),
            ],
        ),
        migrations.CreateModel(
            name='GameObjectRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('game_object_transform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unity.gameobjecttransform')),
            ],
        ),
        migrations.CreateModel(
            name='GameObjectPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('game_object_transform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unity.gameobjecttransform')),
            ],
        ),
        migrations.AddField(
            model_name='gameobject',
            name='layer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unity.layer'),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='unity.gameobject'),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unity.tag'),
        ),
    ]
