# Generated by Django 4.2.30 on 2026-07-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameobject',
            name='pre_existing_parent',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
