# Generated by Django 4.2.30 on 2026-07-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0002_gameobject_pre_existing_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefab_name', models.CharField(max_length=100)),
                ('volume_x', models.FloatField()),
                ('volume_y', models.FloatField()),
                ('volume_z', models.FloatField()),
            ],
        ),
    ]
