# Generated by Django 4.2.30 on 2026-07-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0003_prefab'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameobject',
            name='line_position',
            field=models.IntegerField(default=0),
        ),
    ]
