# Generated by Django 4.2.30 on 2026-07-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0004_gameobject_line_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefab',
            name='volume_x',
        ),
        migrations.RemoveField(
            model_name='prefab',
            name='volume_y',
        ),
        migrations.RemoveField(
            model_name='prefab',
            name='volume_z',
        ),
        migrations.AddField(
            model_name='gameobjecttransform',
            name='prefab',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unity.prefab'),
        ),
        migrations.AlterField(
            model_name='gameobjecttransform',
            name='game_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unity.gameobject'),
        ),
    ]
