# Generated by Django 4.2.30 on 2026-07-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0005_remove_prefab_volume_x_remove_prefab_volume_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameobject',
            name='prefab_name',
        ),
        migrations.AddField(
            model_name='gameobject',
            name='prefab',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unity.prefab'),
        ),
    ]
