# Generated by Django 4.2.30 on 2026-07-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0006_remove_gameobject_prefab_name_gameobject_prefab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameobject',
            name='prefab',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='unity.prefab'),
        ),
    ]
