# Generated by Django 4.2.30 on 2026-07-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_remove_machine_status'),
        ('unity', '0007_alter_gameobject_prefab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameobject',
            name='prefab',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unity.prefab'),
        ),
        migrations.CreateModel(
            name='MachineGameObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unity.gameobject')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
            ],
        ),
    ]
