# Generated by Django 4.2.30 on 2026-07-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_remove_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
